# Generated by Django 3.2 on 2021-11-17 15:28

import data.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_auto_20211116_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='xp_type',
        ),
        migrations.AddField(
            model_name='experiment',
            name='ir_done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='padv_project',
            field=models.TextField(blank=True, choices=[('Individuel', 'Individuel'), ('Pachamama', 'Pachamama'), ("Cultures d'Industries sur Sols Vivants (CISV)", "Cultures d'Industries sur Sols Vivants (CISV)"), ('Sol et autonomie en élevage laitier', 'Sol et autonomie en élevage laitier'), ('Agrohoublon', 'Agrohoublon')], null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='results',
            field=models.TextField(blank=True, choices=[("Maîtrisée & intégrée en routine à l'exploitation", "Maîtrisée & intégrée en routine à l'exploitation"), ("Prometteuse & en cours d'amélioration pour être maîtrisée", "Prometteuse & en cours d'amélioration pour être maîtrisée"), ('Un premier essai, à renouveler pour mieux juger de son potentiel', 'Un premier essai, à renouveler pour mieux juger de son potentiel'), ('Abandonnée car non satisfaisante', 'Abandonnée car non satisfaisante')], null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='surface_type',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Toutes les surfaces', 'Toutes les surfaces'), ('Plusieurs parcelles', 'Plusieurs parcelles'), ('Une parcelle', 'Une parcelle'), ('Une bande', 'Une bande'), ('Des micro-parcelles', 'Des micro-parcelles')]), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='tags',
            field=data.forms.ChoiceArrayField(base_field=models.CharField(choices=[('Maladies', 'Maladies'), ('Insectes et ravageurs', 'Insectes et ravageurs'), ('Adventices', 'Adventices'), ('Environnement & biodiversité', 'Environnement & biodiversité'), ('Diversification', 'Diversification'), ('Autonomie', 'Autonomie'), ('Productivité', 'Productivité'), ('Organisation du travail', 'Organisation du travail'), ('Réduction des charges', 'Réduction des charges'), ('Sol et fertilisation', 'Sol et fertilisation'), ('Équipement et outils', 'Équipement et outils'), ('Autre', 'Autre')], max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='workshop',
            field=models.TextField(blank=True, choices=[('Grandes cultures', 'Grandes cultures'), ("Cultures d'industrie", "Cultures d'industrie"), ('Productions légumières de plein champ', 'Productions légumières de plein champ'), ('Elevage ruminant', 'Elevage ruminant'), ('Elevage monogastrique', 'Elevage monogastrique'), ('Arboriculture', 'Arboriculture'), ('Viticulture', 'Viticulture'), ('Maraîchage diversifié', 'Maraîchage diversifié'), ('PPAM', 'PPAM'), ('Cultures spécialisées', 'Cultures spécialisées')], null=True),
        ),
    ]
