# Generated by Django 3.2 on 2021-11-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0120_rename_padv_project_experiment_padv_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='control_presence',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='ongoing',
        ),
    ]
