# Generated by Django 3.2 on 2021-11-30 15:56

import data.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_auto_20211130_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='livestock_types',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Bovin lait', 'Bovin lait'), ('Bovin allaitant', 'Bovin allaitant'), ('Ovin', 'Ovin'), ('Caprin', 'Caprin'), ('Avicole', 'Avicole'), ('Porcin', 'Porcin'), ('Autre', 'Autre')]), blank=True, default=list, null=True, size=None),
        ),
    ]
