# Generated by Django 3.2 on 2021-12-01 14:53

import data.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_alter_farmer_livestock_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='agriculture_types',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Agriculture Biologique', 'Agriculture Biologique'), ('Agriculture de Conservation des sols (couvert végétaux généralisés, semis direct ou très simplifié, travail du sol réduit, etc.)', 'Agriculture de Conservation des sols (couvert végétaux généralisés, semis direct ou très simplifié, travail du sol réduit, etc.)'), ('Techniques Culturales Simplifiées (couverts végétaux occasionnels, semis simplifié, labour occasionnel, etc.)', 'Techniques Culturales Simplifiées (couverts végétaux occasionnels, semis simplifié, labour occasionnel, etc.)'), ('Agroforesterie', 'Agroforesterie'), ('Conventionnel', 'Conventionnel'), ('Cahier des charges industriel', 'Cahier des charges industriel'), ('Label qualité (Label Rouge, AOP, IGP, etc...)', 'Label qualité (Label Rouge, AOP, IGP, etc...)'), ('Certification environnementale (HVE, etc...)', 'Certification environnementale (HVE, etc...)'), ('Autre', 'Autre')]), blank=True, default=list, null=True, size=None),
        ),
    ]
