# Generated by Django 3.2 on 2021-12-02 08:42

import data.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0128_alter_farmer_agriculture_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='surface_type',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Toutes les surfaces potentiellement adaptées à la mise en place de la pratique', 'Toutes les surfaces potentiellement adaptées à la mise en place de la pratique'), ('Plusieurs parcelles', 'Plusieurs parcelles'), ('Une parcelle', 'Une parcelle'), ('Une bande', 'Une bande'), ('Des micro-parcelles', 'Des micro-parcelles')]), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='agriculture_types',
            field=data.forms.ChoiceArrayField(base_field=models.TextField(choices=[('Agriculture Biologique', 'Agriculture Biologique'), ('Agriculture de Conservation des sols (couvert végétaux généralisés, semis direct ou très simplifié, travail du sol réduit, etc.)', 'Agriculture de Conservation des sols (couvert végétaux généralisés, semis direct ou très simplifié, travail du sol réduit, etc.)'), ('Techniques Culturales Simplifiées (couverts végétaux occasionnels, semis simplifié, labour occasionnel, etc.)', 'Techniques Culturales Simplifiées (couverts végétaux occasionnels, semis simplifié, labour occasionnel, etc.)'), ('Conventionnel', 'Conventionnel'), ('Cahier des charges industriel', 'Cahier des charges industriel'), ('Label qualité (Label Rouge, AOP, IGP, etc...)', 'Label qualité (Label Rouge, AOP, IGP, etc...)'), ('Certification environnementale (HVE, etc...)', 'Certification environnementale (HVE, etc...)'), ('Autre', 'Autre')]), blank=True, default=list, null=True, size=None),
        ),
    ]
